/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.capstone.hotelmanagementsystem;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;

/**
 *
 * @author Admin
 */
public class CheckOutRoomCard extends javax.swing.JPanel {

    /**
     * Creates new form RoomCard
     */
    public CheckOutRoomCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        roomNumber = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        pricePerNight = new javax.swing.JLabel();
        statusBackground = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        persons = new javax.swing.JLabel();
        inAndOut = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        setMaximumSize(new Dimension(Integer.MAX_VALUE, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        image.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        image.setForeground(new java.awt.Color(3, 7, 18));

        roomNumber.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        roomNumber.setForeground(new java.awt.Color(3, 7, 18));
        roomNumber.setText("A234");

        description.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        description.setForeground(new java.awt.Color(3, 7, 18));
        description.setText("A description about this room and more information");

        pricePerNight.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        pricePerNight.setForeground(new java.awt.Color(22, 163, 74));
        pricePerNight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pricePerNight.setText("₱500");

        statusBackground.setBackground(new java.awt.Color(239, 68, 68));

        status.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(3, 7, 18));
        status.setText("Check Out");

        javax.swing.GroupLayout statusBackgroundLayout = new javax.swing.GroupLayout(statusBackground);
        statusBackground.setLayout(statusBackgroundLayout);
        statusBackgroundLayout.setHorizontalGroup(
            statusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusBackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(status)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        statusBackgroundLayout.setVerticalGroup(
            statusBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(status))
        );

        persons.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        persons.setForeground(new java.awt.Color(3, 7, 18));
        persons.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons\\group.png")); // NOI18N
        persons.setText("3");

        inAndOut.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        inAndOut.setForeground(new java.awt.Color(3, 7, 18));
        inAndOut.setText("2025-4-20-10:30 AM - 2025-4-27-10:30:AM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(persons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inAndOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricePerNight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(description)
                            .addComponent(roomNumber))
                        .addGap(255, 401, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(description))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pricePerNight)
                        .addComponent(persons)
                        .addComponent(inAndOut)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.setBackground(new Color(243,244,246));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        this.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JLabel image;
    private javax.swing.JLabel inAndOut;
    private javax.swing.JLabel persons;
    private javax.swing.JLabel pricePerNight;
    private javax.swing.JLabel roomNumber;
    private javax.swing.JLabel status;
    private javax.swing.JPanel statusBackground;
    // End of variables declaration//GEN-END:variables
}
