/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.capstone.hotelmanagementsystem;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Fullscreen when It's start
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SidePanel = new javax.swing.JPanel();
        UserTab = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(Short.MAX_VALUE, 5));
        DashboardTab = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(Short.MAX_VALUE, 5));
        BookingTab = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(Short.MAX_VALUE, 5));
        GuestTab = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(Short.MAX_VALUE, 5));
        RoomTab = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));
        LogoutTab = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        DashboardPanel = new javax.swing.JPanel();
        TopPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        UserPanel = new javax.swing.JPanel();
        TopPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BookingPanel = new javax.swing.JPanel();
        TopPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        GuestPanel = new javax.swing.JPanel();
        TopPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();
        jToolBar3 = new javax.swing.JToolBar();
        jToolBar4 = new javax.swing.JToolBar();
        RoomPanel = new javax.swing.JPanel();
        TopPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomListPanel = new javax.swing.JPanel();
        availableRoomCard1 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        occupiedRoomCard1 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        checkOutRoomCard1 = new com.capstone.hotelmanagementsystem.CheckOutRoomCard();
        checkOutRoomCard2 = new com.capstone.hotelmanagementsystem.CheckOutRoomCard();
        occupiedRoomCard2 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        occupiedRoomCard3 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        availableRoomCard2 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        availableRoomCard3 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        occupiedRoomCard4 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        availableRoomCard4 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        availableRoomCard5 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        availableRoomCard6 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        availableRoomCard7 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        availableRoomCard8 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        occupiedRoomCard5 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        occupiedRoomCard6 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        checkOutRoomCard3 = new com.capstone.hotelmanagementsystem.CheckOutRoomCard();
        occupiedRoomCard7 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        availableRoomCard9 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        availableRoomCard10 = new com.capstone.hotelmanagementsystem.AvailableRoomCard();
        occupiedRoomCard8 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        occupiedRoomCard9 = new com.capstone.hotelmanagementsystem.OccupiedRoomCard();
        TopPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1500, 1000));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        TopPanel.setBackground(new java.awt.Color(55, 48, 163));
        TopPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TopPanel.setPreferredSize(new java.awt.Dimension(1009, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 250, 251));
        jLabel1.setText("HOTEL MANAGEMENT SYSTEM");
        TopPanel.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        getContentPane().add(TopPanel, gridBagConstraints);

        SidePanel.setBackground(new java.awt.Color(67, 56, 202));
        SidePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        SidePanel.setPreferredSize(new java.awt.Dimension(300, 702));
        SidePanel.setLayout(new javax.swing.BoxLayout(SidePanel, javax.swing.BoxLayout.Y_AXIS));

        UserTab.setBackground(new java.awt.Color(249, 250, 253));
        UserTab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UserTab.setForeground(new java.awt.Color(3, 7, 18));
        UserTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons\\management.png")); // NOI18N
        UserTab.setText("User");
        UserTab.setIconTextGap(6);
        UserTab.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        UserTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTabActionPerformed(evt);
            }
        });
        SidePanel.add(UserTab);
        SidePanel.add(filler1);

        DashboardTab.setBackground(new java.awt.Color(249, 250, 253));
        DashboardTab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DashboardTab.setForeground(new java.awt.Color(3, 7, 18));
        DashboardTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons\\statisctics.png")); // NOI18N
        DashboardTab.setText("Dashboard");
        DashboardTab.setIconTextGap(6);
        DashboardTab.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        DashboardTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardTabActionPerformed(evt);
            }
        });
        SidePanel.add(DashboardTab);
        SidePanel.add(filler2);

        BookingTab.setBackground(new java.awt.Color(249, 250, 253));
        BookingTab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BookingTab.setForeground(new java.awt.Color(3, 7, 18));
        BookingTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons\\booking.png")); // NOI18N
        BookingTab.setText("Booking");
        BookingTab.setIconTextGap(6);
        BookingTab.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        BookingTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingTabActionPerformed(evt);
            }
        });
        SidePanel.add(BookingTab);
        SidePanel.add(filler3);

        GuestTab.setBackground(new java.awt.Color(249, 250, 253));
        GuestTab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        GuestTab.setForeground(new java.awt.Color(3, 7, 18));
        GuestTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons\\guest.png")); // NOI18N
        GuestTab.setText("Guest");
        GuestTab.setIconTextGap(6);
        GuestTab.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        GuestTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestTabActionPerformed(evt);
            }
        });
        SidePanel.add(GuestTab);
        SidePanel.add(filler4);

        RoomTab.setBackground(new java.awt.Color(249, 250, 253));
        RoomTab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomTab.setForeground(new java.awt.Color(3, 7, 18));
        RoomTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons\\mattress.png")); // NOI18N
        RoomTab.setText("Room");
        RoomTab.setIconTextGap(6);
        RoomTab.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        RoomTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTabActionPerformed(evt);
            }
        });
        SidePanel.add(RoomTab);
        SidePanel.add(filler6);

        LogoutTab.setBackground(new java.awt.Color(249, 250, 253));
        LogoutTab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LogoutTab.setForeground(new java.awt.Color(3, 7, 18));
        LogoutTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons\\logout.png")); // NOI18N
        LogoutTab.setText("Logout");
        LogoutTab.setIconTextGap(6);
        LogoutTab.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        LogoutTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutTabActionPerformed(evt);
            }
        });
        SidePanel.add(LogoutTab);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.1;
        getContentPane().add(SidePanel, gridBagConstraints);

        MainPanel.setBackground(new java.awt.Color(243, 244, 246));
        MainPanel.setForeground(new java.awt.Color(243, 244, 246));
        MainPanel.setLayout(new java.awt.CardLayout());

        DashboardPanel.setBackground(new java.awt.Color(243, 244, 246));
        DashboardPanel.setForeground(new java.awt.Color(243, 244, 246));
        DashboardPanel.setLayout(new java.awt.BorderLayout());

        TopPanel2.setBackground(new java.awt.Color(49, 46, 129));
        TopPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TopPanel2.setPreferredSize(new java.awt.Dimension(1009, 40));
        TopPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 250, 251));
        jLabel3.setText("    DASHBOARD");
        TopPanel2.add(jLabel3);

        DashboardPanel.add(TopPanel2, java.awt.BorderLayout.PAGE_START);

        MainPanel.add(DashboardPanel, "DashboardCard");

        UserPanel.setBackground(new java.awt.Color(243, 244, 246));
        UserPanel.setForeground(new java.awt.Color(243, 244, 246));
        UserPanel.setLayout(new java.awt.BorderLayout());

        TopPanel1.setBackground(new java.awt.Color(49, 46, 129));
        TopPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TopPanel1.setPreferredSize(new java.awt.Dimension(1009, 40));
        TopPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 250, 251));
        jLabel2.setText("    USER");
        TopPanel1.add(jLabel2);

        UserPanel.add(TopPanel1, java.awt.BorderLayout.PAGE_START);

        MainPanel.add(UserPanel, "UserCard");

        BookingPanel.setBackground(new java.awt.Color(243, 244, 246));
        BookingPanel.setForeground(new java.awt.Color(243, 244, 246));
        BookingPanel.setLayout(new java.awt.BorderLayout());

        TopPanel3.setBackground(new java.awt.Color(49, 46, 129));
        TopPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TopPanel3.setPreferredSize(new java.awt.Dimension(1009, 40));
        TopPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 250, 251));
        jLabel4.setText("    BOOKING");
        TopPanel3.add(jLabel4);

        BookingPanel.add(TopPanel3, java.awt.BorderLayout.PAGE_START);

        MainPanel.add(BookingPanel, "BookingCard");

        GuestPanel.setBackground(new java.awt.Color(243, 244, 246));
        GuestPanel.setForeground(new java.awt.Color(243, 244, 246));
        GuestPanel.setLayout(new java.awt.BorderLayout());

        TopPanel4.setBackground(new java.awt.Color(49, 46, 129));
        TopPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TopPanel4.setPreferredSize(new java.awt.Dimension(1009, 40));
        TopPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 250, 251));
        jLabel5.setText("    GUEST");
        TopPanel4.add(jLabel5);

        GuestPanel.add(TopPanel4, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setRollover(true);
        jTabbedPane1.addTab("Form", jToolBar1);

        jToolBar2.setRollover(true);
        jTabbedPane1.addTab("Active", jToolBar2);

        jToolBar3.setRollover(true);
        jTabbedPane1.addTab("Pending", jToolBar3);

        jToolBar4.setRollover(true);
        jTabbedPane1.addTab("Recent", jToolBar4);

        GuestPanel.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        MainPanel.add(GuestPanel, "GuestCard");

        RoomPanel.setBackground(new java.awt.Color(243, 244, 246));
        RoomPanel.setForeground(new java.awt.Color(243, 244, 246));
        RoomPanel.setLayout(new java.awt.BorderLayout());

        TopPanel5.setBackground(new java.awt.Color(49, 46, 129));
        TopPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TopPanel5.setPreferredSize(new java.awt.Dimension(1009, 40));
        TopPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 250, 251));
        jLabel6.setText("    ROOM");
        TopPanel5.add(jLabel6);

        RoomPanel.add(TopPanel5, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setWheelScrollingEnabled(false);

        RoomListPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        RoomListPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(checkOutRoomCard1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(checkOutRoomCard2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(checkOutRoomCard3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(availableRoomCard10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        RoomListPanel.add(occupiedRoomCard9, gridBagConstraints);

        jScrollPane1.setViewportView(RoomListPanel);

        RoomPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        TopPanel6.setBackground(new java.awt.Color(49, 46, 129));
        TopPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TopPanel6.setPreferredSize(new java.awt.Dimension(1009, 40));
        TopPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setBackground(new java.awt.Color(156, 163, 175));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(3, 7, 18));
        jButton1.setText("Maintenance");
        TopPanel6.add(jButton1);

        jButton2.setBackground(new java.awt.Color(239, 68, 68));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(3, 7, 18));
        jButton2.setText("Check Out");
        TopPanel6.add(jButton2);

        jButton3.setBackground(new java.awt.Color(59, 130, 246));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(3, 7, 18));
        jButton3.setText("Occupied");
        TopPanel6.add(jButton3);

        jButton6.setBackground(new java.awt.Color(59, 130, 246));
        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(3, 7, 18));
        jButton6.setText("Reserve");
        TopPanel6.add(jButton6);

        jButton4.setBackground(new java.awt.Color(22, 163, 74));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(3, 7, 18));
        jButton4.setText("Available");
        TopPanel6.add(jButton4);

        jButton5.setBackground(new java.awt.Color(249, 250, 253));
        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(3, 7, 18));
        jButton5.setText("All");
        TopPanel6.add(jButton5);

        RoomPanel.add(TopPanel6, java.awt.BorderLayout.SOUTH);

        MainPanel.add(RoomPanel, "RoomCard");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.weighty = 1.1;
        getContentPane().add(MainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void ShowCard(String cardName) {
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, cardName + "Card");
    }
    
    private void UserTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTabActionPerformed
        ShowCard("User");
    }//GEN-LAST:event_UserTabActionPerformed

    private void DashboardTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardTabActionPerformed
        ShowCard("Dashboard");
    }//GEN-LAST:event_DashboardTabActionPerformed

    private void BookingTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingTabActionPerformed
        ShowCard("Booking");
    }//GEN-LAST:event_BookingTabActionPerformed

    private void GuestTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestTabActionPerformed
        ShowCard("Guest");
    }//GEN-LAST:event_GuestTabActionPerformed

    private void RoomTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTabActionPerformed
        ShowCard("Room");
    }//GEN-LAST:event_RoomTabActionPerformed

    private void LogoutTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutTabActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookingPanel;
    private javax.swing.JButton BookingTab;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JButton DashboardTab;
    private javax.swing.JPanel GuestPanel;
    private javax.swing.JButton GuestTab;
    private javax.swing.JButton LogoutTab;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RoomListPanel;
    private javax.swing.JPanel RoomPanel;
    private javax.swing.JButton RoomTab;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel TopPanel1;
    private javax.swing.JPanel TopPanel2;
    private javax.swing.JPanel TopPanel3;
    private javax.swing.JPanel TopPanel4;
    private javax.swing.JPanel TopPanel5;
    private javax.swing.JPanel TopPanel6;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton UserTab;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard1;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard10;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard2;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard3;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard4;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard5;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard6;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard7;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard8;
    private com.capstone.hotelmanagementsystem.AvailableRoomCard availableRoomCard9;
    private com.capstone.hotelmanagementsystem.CheckOutRoomCard checkOutRoomCard1;
    private com.capstone.hotelmanagementsystem.CheckOutRoomCard checkOutRoomCard2;
    private com.capstone.hotelmanagementsystem.CheckOutRoomCard checkOutRoomCard3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard1;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard2;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard3;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard4;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard5;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard6;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard7;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard8;
    private com.capstone.hotelmanagementsystem.OccupiedRoomCard occupiedRoomCard9;
    // End of variables declaration//GEN-END:variables
}
